openapi: 3.0.0
info:
  title: 2DO PARCIAL BACKEND
  version: 1.0.0
paths:
  /api/example:
    get:
      summary: Get example data
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string